# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx5G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.vfs.watch=true
org.gradle.caching=true
# Experimental function, can throw errors!
org.gradle.configureondemand=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.5
loom_version=1.18-SNAPSHOT

# Fabric API
fabric_api_version=0.161.0+26.2

# Modmenu
modmenu_version=20.0.3

# Mod Properties
mod_version=1.2.0
maven_group=net.sn0wix_.keepthatinventoryopen
archives_base_name=KeepThatInventoryOpen
mc_compatibility_version=26.2